### ISSUE TITLE
Broken links under Perform Cloud Insight connection prerequisites

### ISSUE THREAD

**Issue by akarwasz** [NetAppDocs/astra-data-store#11]
Page: [Monitor metrics with Cloud Insights](https://docs.netapp.com/us-en/astra-data-store/use/monitor-with-cloud-insights.html)

Two broken links when you click:

Install the Astra Data Store Monitoring Operator.
Install the kubectl-astrads binary 

both returns 404, file not found

**Comment by amgrissino** [comment]
Thank you akarwasz for the catch. We'll correct these 2 links. 

Meanwhile if you need the info now, the correct links are: 

- Install the Astra Data Store Monitoring Operator - https://docs.netapp.com/us-en/astra-data-store/get-started/install-ads.html#install-the-monitoring-operator
- Install the kubectl-astrads binary  - https://docs.netapp.com/us-en/astra-data-store/get-started/install-ads.html  

Actually, both of these links are subsections on the https://docs.netapp.com/us-en/astra-data-store/get-started/install-ads.html  page.

**Comment by amgrissino** [comment]
Links updated and live: https://docs.netapp.com/us-en/astra-data-store/use/monitor-with-cloud-insights.html 
Thank you again for your comments.
