### ISSUE TITLE
Typo in the kubectl delete command

### ISSUE THREAD

**Issue by akarwasz** [NetAppDocs/astra-data-store#16]
Page: [Uninstall Astra Data Store preview](https://docs.netapp.com/us-en/astra-data-store/use/uninstall-ads.html)

Please edit this line:
kubectl delete astradsversion atradsversion -n astrads-system

to 
kubectl delete astradsversion astradsversion -n astrads-system

**Comment by netapp-dbagwell** [comment]
Good catch, @akarwasz. We're on it.

**Comment by netapp-dbagwell** [comment]
Change is live: https://docs.netapp.com/us-en/astra-data-store/use/uninstall-ads.html#delete-the-license
