### ISSUE TITLE
Remove SATA drives from supported disks

### ISSUE THREAD

**Issue by akarwasz** [NetAppDocs/astra-data-store#19]
Page: [Astra Data Store preview requirements](https://docs.netapp.com/us-en/astra-data-store/get-started/requirements.html)

Please remove SATA disks from supported drivers types across ADS Preview documentation: 

Based on burt1442598:
"SATA SAMSUNG drives are not officially supported for Astra DS in the field"

"...it was decided to not include support for Ubuntu SATA devices in the Preview release."

Kunal Raina can provide more if needed

**Comment by netapp-mwallis** [comment]
Hi @akarwasz - Thanks for letting us know about the change.  We'll get this fix in to the documentation this week.

**Comment by netapp-mwallis** [comment]
Hi @akarwasz, this change is complete and should be visible at the same requirements link: https://docs.netapp.com/us-en/astra-data-store/get-started/requirements.html

Thanks!
