### ISSUE TITLE
Incorrect comma in example backend JSON

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/astra-data-store#26]
Page: [Set up Astra Data Store preview components](https://docs.netapp.com/us-en/astra-data-store/get-started/setup-ads.html)

In the section "Set up Astra Data Store as storage backend":

The example storage backend configuration JSON has an extra comma that makes it invalid JSON. After "bronze" in the "premium" definition.

> {
    "version": 1,
    "storageDriverName": "astrads-nas",
    "storagePrefix": "",
    "cluster": "example-1234584",
    "namespace": "astrads-system",
    "autoExportPolicy": true,
    "autoExportCIDRs": ["0.0.0.0/0"],
    "kubeconfig": "<base64_output_of_kubeconf_json>",
    "debugTraceFlags": {"method": true, "api": true},
    "labels": {"cloud": "on-prem", "creator": "trident-dev"},
    "defaults": {
        "qosPolicy": "bronze"
    },
    "storage": [
        {
            "labels": {
                "performance": "extreme"
            },
            "defaults": {
                "qosPolicy": "bronze"
            }
        },
        {
            "labels": {
                "performance": "premium"
            },
            "defaults": {
                "qosPolicy": "bronze",&#x274C;
            }
        },
        {
            "labels": {
                "performance": "standard"
            },
            "defaults": {
                "qosPolicy": "bronze"
            }
        }
    ]
}

**Comment by netapp-dbagwell** [comment]
Thanks @wonderland. Correction is now live: https://docs.netapp.com/us-en/astra-data-store/get-started/setup-ads.html#set-up-astra-data-store-as-storage-backend
