### ISSUE TITLE
Extra character

### ISSUE THREAD

**Issue by netapp-igorr** [NetAppDocs/astra-data-store#35]
Page: [Install Astra Data Store preview on Red Hat OpenShift Container Platform](https://docs.netapp.com/us-en/astra-data-store/get-started/install-ads-openshift.html)

Prepare the worker nodes > Step 1:
sudo cp /var/lib/kubelet/config.json /var/lib/kubelet/config.yaml**`**

I assume that ` in the end of the command should be removed.

**Comment by netapp-dbagwell** [comment]
Thanks for the catch, @netapp-igorr. There was an extraneous adoc character coming through in the HTML. The page has been updated.
