### ISSUE TITLE
NFS requirements for Ubuntu Env

### ISSUE THREAD

**Issue by hayatokurahashi** [NetAppDocs/astra-data-store#39]
Page: [Astra Data Store preview requirements](https://docs.netapp.com/us-en/astra-data-store/get-started/requirements.html)

I have feedback on this statement :

- The NFSv4.1 client/server must be installed on Kubernetes clusters.
- The nfs-utils package must be installed on worker nodes.

If I install NFS server pakcage on Ubuntu, NFS mount doesn't complete because NFS mount request is intercepted by OS. Expectation after ADS installation is Port:2049 is monitored by firefly. But  it is still monitored by "NFS Service" of OS.
I installed nfs-kernel-server for NFS Server, but "NFS mount" issue was resolved by uninstalling it from OS.

There is no nfs-utils pakcage for Ubuntu, but NFS client is installed in default.
I suggests to change this statement.

Thanks,

My email address is hayato.kurahashi@netapp.com

**Comment by netapp-mwallis** [comment]
Hi @hayatokurahashi,

Apologies for the difficulties this caused, and thank you for letting us know about this challenge.  We'll confirm here and make the suggested change (and improve the clarity here if we can).   I've opened https://jira.ngage.netapp.com/browse/DOC-4069 to track this change.

Thanks,
Michael

**Comment by netapp-mwallis** [comment]
@hayatokurahashi, the NFS package guidance has been removed from the Astra Data Store preview requirements documentation.   Thanks again for helping us improve our docs.

--Michael
