### ISSUE TITLE
syntax error...

### ISSUE THREAD

**Issue by mdmiller99** [NetAppDocs/astra-data-store#41]
Page: [Manage the cluster](https://docs.netapp.com/us-en/astra-data-store/use/maintain-cluster.html)

Please update the cli syntax to include "--cluster" instead of "-cluster":

kubectl astrads nodes add –cluster <cluster-name>

This is in steps 1b and 2.

**Comment by netapp-dbagwell** [comment]
Thanks for the feedback @mdmiller99. We'll get this taken care of.

**Comment by netapp-dbagwell** [comment]
@mdmiller99 changes are live: https://docs.netapp.com/us-en/astra-data-store/use/maintain-cluster.html#add-a-node. Thanks again.
