### ISSUE TITLE
ASTRASD 133

### ISSUE THREAD

**Issue by gimmeyopods** [NetAppDocs/astra-data-store#48]
Page: [Install Astra Data Store preview](https://docs.netapp.com/us-en/astra-data-store/get-started/install-ads.html)

Internal customer noted that this documentation is incorrect: https://docs.netapp.com/us-en/astra-data-store/get-started/install-ads.html#ocp-only-prepare-the-worker-nodes

https://jira.ngage.netapp.com/browse/ASTRASD-133

The YAML copy does not need to be placed onto each node; it already exists. Adding it creates an error as listed in the ticket.

Please remove the section in the documentation stating the YAML file needs to be placed into each node as it will lead to errors during installation/configuration. We have also ran this by engineering who agreed.

Thank you.

**Comment by netapp-dbagwell** [comment]
Thanks @gimmeyopods for your feedback. We'll look into this and update status in this ticket.

**Comment by netapp-dbagwell** [comment]
@gimmeyopods can you please confirm if this was with ADS preview (21.12) or patch (2021.12.1)? Thanks

**Comment by amgrissino** [comment]
Understand that it's part of 2021.12.1 release.

**Comment by netapp-joey** [comment]
Looks like Shiv's email reply didn't make it to the thread. Here it is:

-----

Hi Dave,

As per the customers response, it was ‘Preview build 2021.12.01’

Thank you.

Sincerely,
--
Shivanjali Pothan

**Comment by amgrissino** [comment]
Just checked the ticket. Still being reviewed. Just checking in for you.

**Comment by netapp-dbagwell** [comment]
Sorry for the delay. Engineering has confirmed that the section is no longer relevant for the Astra Data Store preview patch. It has been removed from the procedure: https://docs.netapp.com/us-en/astra-data-store/get-started/install-ads.html

**Comment by gimmeyopods** [comment]
Hi Dave,

As per the customers response, it was 'Preview build 2021.12.01'

Thank you.

Sincerely,
--
Shivanjali Pothan
Technical Support Engineer II - Data Protection
Technical Support Center

***@***.***

My normal working hours are Monday - Friday, 7 a.m. - 3 p.m. EST.

For technical assistance on a new or existing case, please call:
* US & Canada 888-4-NETAPP // * EMEA/Europe  00-800-44-638277 // * Asia/Pacific  800-8008-0800

You may also get Support on the Web at http://mysupport.netapp.com.

Everyone in the NetApp Technical Support Center is committed to providing the highest level of customer satisfaction.  If you believe that the level of support can be improved, please contact my manager, Ryan Jackson, at ***@***.***

[A picture containing drawing  Description automatically generated]<https://www.netapp.com/us/index.aspx>
