### ISSUE TITLE
Update Kubernetes worker node resource requirements

### ISSUE THREAD

**Issue by akarwasz** [NetAppDocs/astra-data-store#5]
Page: [Astra Data Store preview requirements](https://docs.netapp.com/us-en/astra-data-store/get-started/requirements.html)

Please update the requirements in the "Kubernetes worker node resource requirements" table.
For both Minimum and Maximum tables please change:
Number of vCPUs from 9 to 10
RAM from 34GiB to 35GiB

This was discovered during cluster deployment were the settings are set as below: "requiredcpu":10,"requiredmembytes":37580963840

**Comment by netapp-dbagwell** [comment]
@akarwasz thanks for the catch. We're addressing this and will keep you updated in this comment thread.

**Comment by netapp-mwallis** [comment]
@akarwasz  Can you take a look at the draft change at the below link?  If this is good to go, let me know and I'll make the change public.  Thanks!
https://review.docs.netapp.com/us-en/astra-data-store_mw-hotfix-gh-issues-5-6/get-started/requirements.html#kubernetes-worker-node-resource-requirements

**Comment by akarwasz** [comment]
Looks good to me. thanks!

**Comment by netapp-mwallis** [comment]
@akarwasz Content is now public. Thanks.
