### ISSUE TITLE
Prometheus and Grafana install links...

### ISSUE THREAD

**Issue by mdmiller99** [NetAppDocs/astra-data-store#50]
Page: [Monitor metrics with Prometheus and Grafana](https://docs.netapp.com/us-en/astra-data-store/use/monitor-with-prometheus-grafana.html)

The links for install instructions do not cover installing into a kubernetes cluster.  Please consider updating these links to point to the following KBs:

https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/How_to_deploy_Prometheus_with_Astra_Data_Store

https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/How_to_set_up_Grafana_for_monitoring_Astra_Data_Store_cluster

**Comment by netapp-mwallis** [comment]
Hi @mdmiller99, thanks for bringing this to our attention, and thanks for the more specific installation links.  We'll get the links updated in the next release of the Astra Data Store documentation. I've opened https://jira.ngage.netapp.com/browse/DOC-4169 to track this improvement.

Thank you,
Michael

**Comment by netapp-mwallis** [comment]
Hi @mdmiller99, this issue has been fixed; the topic now uses the KB article links for installation instead of the previous links.  I'll close this issue. 
Thanks again, Michael
