### ISSUE TITLE
Astra Control Center requirements

### ISSUE THREAD

**Issue by netapp-igorr** [NetAppDocs/astra-data-store#6]
Page: [Astra Data Store preview requirements](https://docs.netapp.com/us-en/astra-data-store/get-started/requirements.html)

Hello Team,

I suggest to add an advice to check [ACC requirements ](https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html) as well if ADS cluster will be managed by ACC.

For example, a cluster must have 3 controller nodes to be managed from Astra Control Center. ADS docs do not include any controller node requirements.

**Comment by netapp-dbagwell** [comment]
Thanks @netapp-igorr. We're addressing this and will reply when we have an update.

**Comment by netapp-mwallis** [comment]
@netapp-igorr  Can you take a look at the draft for this change at the below link?  If this is good to go, let me know and I'll make the change public.  Thanks!
https://review.docs.netapp.com/us-en/astra-data-store_mw-hotfix-gh-issues-5-6/get-started/requirements.html#kubernetes-worker-node-resource-requirements

**Comment by netapp-igorr** [comment]
@netapp-mwallis Looks good, thank you

**Comment by netapp-mwallis** [comment]
@netapp-igorr Content is now public. Thanks.
