### ISSUE TITLE
No efficiency details

### ISSUE THREAD

**Issue by deansteadman** [NetAppDocs/astra-data-store#65]
Page: [Storage efficiency in Astra Data Store](https://docs.netapp.com/us-en/astra-data-store/concepts/storage-efficiency.html)

This page doesn't go into any detail on how storage efficiencies are designed or what benefits they provide. The link to get more information goes to the root of the ONTAP docs. Are we implying that we provide the same efficiencies? 

We need to detail how data is dispersed and replicated between nodes. We also need to provide a base efficiency rating as well as ranges for dedup and compression.

**Comment by netapp-dbagwell** [comment]
@deansteadman thanks. I've created a internal doc ticket to address this request. We'll keep you updated on progress.

**Comment by netapp-dbagwell** [comment]
@deansteadman closing this GitHub issue. The request will instead be tracked internally and you have been added as a watcher.
