### ISSUE TITLE
ads_backend.json improvements

### ISSUE THREAD

**Issue by akarwasz** [NetAppDocs/astra-data-store#9]
Page: [Set up Astra Data Store preview components](https://docs.netapp.com/us-en/astra-data-store/get-started/setup-ads.html)

i.
Please replace the example conversion with:
"python3 -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=None)' < ~/.kube/config > kubeconf.json"

Currently is:
python3 -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=None)' < kubeconfig_filepath > kubeconf.json

ii. add a line:
"Note: the value should always have == in the end"

**Comment by netapp-mwallis** [comment]
Thanks @akarwasz. We'll work on this and ask you to review before the change goes public.

**Comment by netapp-dbagwell** [comment]
@akarwasz is this ok?

.. For the `"kubeconfig"` value, do the following:
... Convert and minimize the .kube/config YAML file to JSON format without spaces:
+
Example conversion:
+
----
python3 -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=None)' < ~/.kube/config > kubeconf.json
----

... Encode as base64 and use the base64 output for the `"kubeconfig"` value:
+
Example encoding:
+
----
cat kubeconf.json | base64 | tr -d '\n'
----
+
NOTE: The response value should always have `==` at the end.

**Comment by akarwasz** [comment]
Looks good to me. Thanks!

**Comment by netapp-dbagwell** [comment]
After validation, it was requested that I remove the suggested note. There are additional changes in this topic published as well: https://github.com/NetAppDocs/astra-data-store/pull/12. Changes to the public repo are now live. Thanks again, @akarwasz for the feedback.
